package net.anweisen.cloudapi.driver.support;

/**
 * @author anweisen | https://github.com/anweisen
 * @since 1.0
 */
public enum SupportFlag {

	USER_PERMISSION_POTENCY,
	USER_PERMISSION_TIMEOUT,
	USER_PERMISSION_TASK_GROUP,
	USER_GROUP_TIMEOUT,

	GROUP_PERMISSION_POTENCY,
	GROUP_PERMISSION_TIMEOUT,
	GROUP_SORTID,
	GROUP_PREFIX,
	GROUP_SUFFIX,
	GROUP_COLOR,
	GROUP_DISPLAYNAME,

	EVENT_LISTENER_PRIORITY,
	EVENT_LISTENER_CHANNEL,

	CHANNEL_MESSAGING,
	CHANNEL_QUERY_MESSAGING,

	SERVICE_RUN_COMMAND,
	SERVICE_GET_LOG,
	SERVICE_PROPERTIES,

	TASK_MAINTENANCE,
	TASK_GROUPS,
	TASK_START_FORBIDDING,
	TASK_PROPERTIES,
	TASK_DISABLE_IP_REWRITES,
	TASK_STATIC_SERVICES,

}
