name: CloudAPI
version: 1.0
api-version: 1.13
author: anweisen
main: "net.anweisen.cloudapi.simplecloud.wrapper.launcher.BukkitPlugin"
website: https://github.com/anweisen/CloudAPI
depend: [ SimpleCloud-Plugin ]
